name: Generate Professional Portfolio
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Portfolio Generator
        uses: solorzanomarcelo/portfolio-generator@main
